### ISSUE TITLE
morphism  are derived incorrectly for polymorphic variants

### ISSUE THREAD

**Issue by ivg** [janestreet/ppx_variants_conv#3] opened 2016-03-02 18:25 UTC
I'm not sure whether the problem is on the `mli` side, or on a `ml` side, but they don't match.

Given a simple example:

```
module type Arch = sig
  type t = [
    | `x86
    | `arm
  ] [@@deriving bin_io, compare, enumerate, sexp, variants]
end
```

The following is derived:

```
module type Arch =
  sig
    type t = [ `arm | `x86 ]
    val bin_t : t Core_kernel.Std.Bin_prot.Type_class.t
    val bin_read_t : t Core_kernel.Std.Bin_prot.Read.reader
    val __bin_read_t__ : (int -> t) Core_kernel.Std.Bin_prot.Read.reader
    val bin_reader_t : t Core_kernel.Std.Bin_prot.Type_class.reader
    val bin_size_t : t Core_kernel.Std.Bin_prot.Size.sizer
    val bin_write_t : t Core_kernel.Std.Bin_prot.Write.writer
    val bin_writer_t : t Core_kernel.Std.Bin_prot.Type_class.writer
    val compare : t -> t -> int
    val all : t list
    val t_of_sexp : Sexplib.Sexp.t -> t
    val __t_of_sexp__ : Sexplib.Sexp.t -> t
    val sexp_of_t : t -> Sexplib.Sexp.t
    val arm : t
    val x86 : t
    module Variants :
      sig
        val arm : t Variantslib.Variant.t
        val x86 : t Variantslib.Variant.t
        val fold :
          init:'acc__ ->
          x86:('acc__ -> t Variantslib.Variant.t -> 'acc__) ->
          arm:('acc__ -> t Variantslib.Variant.t -> 'acc__) -> 'acc__
        val iter :
          x86:(t Variantslib.Variant.t -> unit) ->
          arm:(t Variantslib.Variant.t -> unit) -> unit
        val map :
          t ->
          x86:(t Variantslib.Variant.t -> 'result__) ->
          arm:(t Variantslib.Variant.t -> 'result__) -> 'result__
        val descriptions : (string * int) list
      end
  end
```

As a result, we can't satisfy the interface:

```
module Arch : Arch = struct
  type t = [
    | `arm
    | `x86
  ] [@@deriving bin_io, compare, enumerate, sexp, variants]
end
```

Gives an error:

```
Error: Signature mismatch:
       ...
       In module Variants:
       Values do not match:
         val fold :
           init:'a ->
           arm:('a -> [> `arm ] Variantslib.Variant.t -> 'b) ->
           x86:('b -> [> `x86 ] Variantslib.Variant.t -> 'c) -> 'c
       is not included in
         val fold :
           init:'acc__ ->
           x86:('acc__ -> t Variantslib.Variant.t -> 'acc__) ->
           arm:('acc__ -> t Variantslib.Variant.t -> 'acc__) -> 'acc__
```

**Comment by trefis** [comment] 2016-03-03 12:09
I didn't manage to reproduce the problem...
Which version of ppx_variants_conv and ppx_driver are you using?

**Comment by ivg** [comment] 2016-03-03 12:57
`113.24.00` for both. OCaml 4.02.3

**Comment by yminsky** [comment] 2016-09-25 06:44
I also can't reproduce on a recent release. I'm assuming that means this is fixed, so closing.

**Closed as completed by yminsky** 2016-09-25 06:44 UTC
